-- AlterTable
ALTER TABLE `Lang` ADD COLUMN `deletedAt` DATETIME(3) NULL,
    ADD COLUMN `isDeleted` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `Media` ADD COLUMN `createBy` VARCHAR(191) NULL,
    ADD COLUMN `updateBy` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `MediaTranslation` ADD COLUMN `createBy` VARCHAR(191) NULL,
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `deletedAt` DATETIME(3) NULL,
    ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `updateBy` VARCHAR(191) NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `Menu` MODIFY `updatedAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `MenuTranslation` ADD COLUMN `createBy` VARCHAR(191) NULL,
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `overview` VARCHAR(191) NULL,
    ADD COLUMN `subTitle` VARCHAR(191) NULL,
    ADD COLUMN `updateBy` VARCHAR(191) NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NULL,
    MODIFY `slug` VARCHAR(191) NULL;
