-- CreateTable
CREATE TABLE `auditlog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `user` VARCHAR(191) NOT NULL,
    `ip` VARCHAR(191) NOT NULL,
    `urlApi` VARCHAR(191) NOT NULL,
    `urlFe` VARCHAR(191) NOT NULL,
    `methodApi` VARCHAR(191) NOT NULL,
    `bodyApi` LONGTEXT NOT NULL,
    `menuId` INTEGER NOT NULL,
    `menuLabel` VARCHAR(191) NOT NULL,
    `pageId` INTEGER NOT NULL,
    `PageLabel` VARCHAR(191) NOT NULL,
    `createBy` VARCHAR(191) NOT NULL,
    `updateBy` VARCHAR(191) NOT NULL,
    `updateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
